using System.Text;
using System.Text.RegularExpressions;

namespace ASMForge.Core.Pseudocode;

/// <summary>Result of <see cref="PseudocodeCompiler.Compile"/>: MIPS assembly, or the errors that prevented it.</summary>
public sealed record PseudocodeResult(string Assembly, IReadOnlyList<PseudocodeError> Errors)
{
    public bool Success => Errors.Count == 0;
}

/// <summary>
/// Deterministic pseudocode-to-MIPS translator (not AI). Pseudocode is C-like: int variables and arrays,
/// if/else, while, do-while, for, break/continue, print/printChar/readInt/readChar/exit, and C operators with
/// short-circuit &amp;&amp; / ||. The output follows a hand-written course style: the pseudocode as a comment block,
/// variables in $s registers, named strings and labels, and short trailing comments.
/// </summary>
public static class PseudocodeCompiler
{
    public static PseudocodeResult Compile(string source, string? sourceName = null)
    {
        var errors = new List<PseudocodeError>();
        var original = (source ?? string.Empty).Replace("\r\n", "\n");
        var prepared = UncommentHashPrefixedCode(original);
        var tokens = new PseudocodeLexer(prepared, errors).Tokenize();
        var program = new PseudocodeParser(tokens, prepared, errors).ParseProgram();
        if (errors.Count == 0)
        {
            var assembly = new PseudocodeGenerator(errors).Generate(program, sourceName, original);
            if (errors.Count == 0) return new PseudocodeResult(assembly, errors);
        }
        return new PseudocodeResult(string.Empty, errors.OrderBy(e => e.Line).ThenBy(e => e.Column).ToList());
    }

    // Code pasted from an assembly file's comment block ("# int i = 1;") is accepted as-is: when every non-blank
    // line starts with '#', each leading '#' becomes a space (so line/column numbers stay the same).
    private static string UncommentHashPrefixedCode(string source)
    {
        var lines = source.Split('\n');
        var nonBlank = lines.Where(l => l.Trim().Length > 0).ToList();
        if (nonBlank.Count == 0 || !nonBlank.All(l => l.TrimStart().StartsWith('#'))) return source;
        return string.Join("\n", lines.Select(l =>
        {
            var hash = l.IndexOf('#');
            return hash < 0 ? l : l[..hash] + " " + l[(hash + 1)..];
        }));
    }
}

/// <summary>
/// Turns the syntax tree into commented MIPS. Scalar variables live in $s0-$s7 (extra ones in .data);
/// arrays live in .data; expressions use $t0-$t9.
/// </summary>
internal sealed class PseudocodeGenerator
{
    private sealed class Variable
    {
        public required string Name { get; init; }
        public string? Register { get; init; }   // $sN for scalars kept in a register
        public string? Label { get; init; }      // .data label for arrays and scalars that did not fit in registers
        public int? ArraySize { get; init; }
        public List<int> InitialWords { get; } = new();
    }

    public const string Header = "# Generated by the ASMForge Pseudocode Generator";
    private const int TempRegisters = 10;
    private const int SavedRegisters = 8;
    private const int CommentColumn = 32;

    private readonly List<PseudocodeError> _errors;
    private readonly StringBuilder _text = new();
    private readonly Dictionary<string, Variable> _variables = new(StringComparer.Ordinal);
    private readonly List<Variable> _declarationOrder = new();
    private readonly Dictionary<string, string> _stringLabels = new(StringComparer.Ordinal);
    private readonly List<(string Label, string Text)> _strings = new();
    private readonly HashSet<string> _usedLabels = new(StringComparer.OrdinalIgnoreCase) { "main" };
    private readonly Dictionary<string, int> _labelNumbers = new(StringComparer.Ordinal);
    private readonly Stack<(string Continue, string Break)> _loops = new();
    private int _savedRegistersUsed;
    private bool _lastLineBlank = true;
    private bool _lastLineLabel;

    public PseudocodeGenerator(List<PseudocodeError> errors) => _errors = errors;

    public string Generate(List<Stmt> program, string? sourceName, string originalSource)
    {
        foreach (var statement in program) EmitStatement(statement);

        var output = new StringBuilder();
        output.AppendLine($"{Header}{(sourceName is null ? "" : $" from {sourceName}")}.");

        // Words first (aligned at the start of .data), then strings.
        var memory = _declarationOrder.Where(v => v.Label is not null).ToList();
        if (memory.Count > 0 || _strings.Count > 0)
        {
            output.AppendLine(".data");
            foreach (var variable in memory)
            {
                var line = variable.ArraySize is { } size && variable.InitialWords.Count == 0
                    ? $"{variable.Label}: .space {size * 4}"
                    : $"{variable.Label}: .word {string.Join(", ", variable.InitialWords)}";
                output.AppendLine(WithComment(line, variable.ArraySize is { } n ? $"int {variable.Name}[{n}]" : $"int {variable.Name}"));
            }
            foreach (var (label, text) in _strings)
                output.AppendLine($"{label}: .asciiz \"{text}\"");
            output.AppendLine();
        }

        output.AppendLine(".text");
        output.AppendLine(".globl main");
        output.AppendLine();
        foreach (var line in PseudocodeCommentBlock(originalSource)) output.AppendLine(line);
        output.AppendLine();

        var registers = _declarationOrder.Where(v => v.Register is not null).ToList();
        if (registers.Count > 0)
            output.AppendLine("# Registers: " + string.Join(", ", registers.Select(v => $"{v.Register} = {v.Name}")));
        if (memory.Count > 0)
            output.AppendLine("# In memory (.data): " + string.Join(", ", memory.Select(v => v.Name)));
        if (registers.Count > 0 || memory.Count > 0) output.AppendLine();

        output.AppendLine("main:");
        output.Append(_text);
        if (!_lastLineBlank && !_lastLineLabel) output.AppendLine(); // the exit code follows a final label directly
        output.AppendLine(WithComment("    li $v0, 10", "Select exit syscall"));
        output.AppendLine(WithComment("    syscall", "Exit program"));
        return output.ToString().Replace("\r\n", "\n");
    }

    // The pseudocode as written, as one '#' comment block (lines already starting with '#' are kept as they are).
    private static IEnumerable<string> PseudocodeCommentBlock(string source)
    {
        var lines = source.Split('\n').Select(l => l.TrimEnd()).ToList();
        while (lines.Count > 0 && lines[0].Length == 0) lines.RemoveAt(0);
        while (lines.Count > 0 && lines[^1].Length == 0) lines.RemoveAt(lines.Count - 1);
        return lines.Select(l => l.TrimStart().StartsWith('#') ? l.TrimStart() : l.Length == 0 ? "#" : "# " + l);
    }

    // ---- Statements ----

    private void EmitStatement(Stmt statement)
    {
        switch (statement)
        {
            case BlockStmt block:
                foreach (var inner in block.Statements) EmitStatement(inner);
                break;

            case DeclarationStmt declaration:
                foreach (var declarator in declaration.Declarators) EmitDeclarator(declarator);
                break;

            case AssignStmt assign:
                var value = assign.Op == "=" ? assign.Value : new BinaryExpr(assign.Line, assign.Column, assign.Op, assign.Target, assign.Value);
                EmitStore(assign.Target, value, Trim(assign.Source));
                break;

            case IncrementStmt increment:
                EmitStore(increment.Target, new BinaryExpr(increment.Line, increment.Column, "+", increment.Target,
                    new NumberExpr(increment.Line, increment.Column, increment.Delta, false)), Trim(increment.Source));
                break;

            case IfStmt ifStmt:
                EmitIf(ifStmt);
                break;

            case WhileStmt loop:
            {
                var labels = NewLabels("loop", "endLoop");
                Label(labels[0], loop.Source);
                JumpIfFalse(loop.Condition, labels[1], 0);
                EmitLoopBody(loop.Body, labels[0], labels[1]);
                Instruction($"j {labels[0]}", "Repeat the loop");
                Label(labels[1], "End of loop");
                break;
            }

            case DoWhileStmt loop:
            {
                var labels = NewLabels("doLoop", "doCondition", "endDo");
                Label(labels[0], "do");
                EmitLoopBody(loop.Body, labels[1], labels[2]);
                Label(labels[1], loop.ConditionSource);
                JumpIfTrue(loop.Condition, labels[0], 0);
                Label(labels[2], "End of loop");
                break;
            }

            case ForStmt loop:
            {
                var labels = NewLabels("forLoop", "forNext", "endFor");
                if (loop.Init is not null) EmitStatement(loop.Init);
                Label(labels[0], loop.Source);
                if (loop.Condition is not null) JumpIfFalse(loop.Condition, labels[2], 0);
                EmitLoopBody(loop.Body, labels[1], labels[2]);
                Label(labels[1], "Next iteration");
                if (loop.Step is not null) EmitStatement(loop.Step);
                Instruction($"j {labels[0]}", "Repeat the loop");
                Label(labels[2], "End of loop");
                break;
            }

            case BreakStmt brk:
                if (_loops.Count == 0) Error(brk, "'break' can only be used inside a loop.");
                else Instruction($"j {_loops.Peek().Break}", "break");
                break;

            case ContinueStmt cont:
                if (_loops.Count == 0) Error(cont, "'continue' can only be used inside a loop.");
                else Instruction($"j {_loops.Peek().Continue}", "continue");
                break;

            case PrintStmt print:
                foreach (var argument in print.Arguments) EmitPrint(argument, print.AsChar);
                break;

            case ExitStmt:
                Instruction("li $v0, 10", "Select exit syscall");
                Instruction("syscall", "Exit program");
                break;

            case ExpressionStmt expression:
                Value(expression.Expression, 0);
                break;
        }
    }

    private void EmitLoopBody(Stmt body, string continueLabel, string breakLabel)
    {
        _loops.Push((continueLabel, breakLabel));
        EmitStatement(body);
        _loops.Pop();
    }

    private void EmitIf(IfStmt ifStmt)
    {
        var labels = ifStmt.Else is null ? NewLabels("endIf") : NewLabels("else", "endIf");
        var end = labels[^1];
        JumpIfFalse(ifStmt.Condition, labels[0], 0, Trim(ifStmt.Source));
        EmitStatement(ifStmt.Then);
        if (ifStmt.Else is not null)
        {
            Instruction($"j {end}", "Skip the else part");
            Label(labels[0], ifStmt.Else is IfStmt ? null : "else");
            EmitStatement(ifStmt.Else);
        }
        Label(end, null);
    }

    private void EmitDeclarator(Declarator declarator)
    {
        var note = declarator.ArraySize is { } count ? $"int {declarator.Name}[{count}]"
            : declarator.Init is null ? $"int {declarator.Name}" : $"int {declarator.Name} = {Text(declarator.Init)}";

        if (_variables.TryGetValue(declarator.Name, out var existing))
        {
            // Re-declaring is allowed (e.g. two loops both using "for (int i = 0; ...)") as long as the kind matches.
            if (existing.ArraySize != declarator.ArraySize)
                Error(declarator.Line, declarator.Column, $"'{declarator.Name}' is already declared as {(existing.ArraySize is null ? "a variable" : $"an array of {existing.ArraySize}")}.");
            else if (declarator.Init is not null)
                EmitStore(new VariableExpr(declarator.Line, declarator.Column, declarator.Name), declarator.Init, note);
            return;
        }

        if (declarator.ArraySize is { } size)
        {
            var array = new Variable { Name = declarator.Name, Label = DataLabel(declarator.Name), ArraySize = size };
            if (declarator.ArrayInit is { } values)
            {
                if (values.Count > size)
                    Error(declarator.Line, declarator.Column, $"Array '{declarator.Name}' has room for {size} values but {values.Count} were given.");
                foreach (var v in values)
                {
                    if (Fold(v) is { } constant) array.InitialWords.Add(constant);
                    else Error(v, "Array starting values must be numbers.");
                }
                while (array.InitialWords.Count < size) array.InitialWords.Add(0);
            }
            Add(array);
            return;
        }

        // Scalars get the next $s register; past $s7 they live in .data.
        var variable = _savedRegistersUsed < SavedRegisters
            ? new Variable { Name = declarator.Name, Register = $"$s{_savedRegistersUsed++}" }
            : new Variable { Name = declarator.Name, Label = DataLabel(declarator.Name) };
        if (variable.Label is not null) variable.InitialWords.Add(0);
        Add(variable);
        if (declarator.Init is not null)
            EmitStore(new VariableExpr(declarator.Line, declarator.Column, declarator.Name), declarator.Init, note);
    }

    private void Add(Variable variable)
    {
        _variables[variable.Name] = variable;
        _declarationOrder.Add(variable);
    }

    private void EmitStore(Expr target, Expr value, string note)
    {
        switch (target)
        {
            case VariableExpr variable when Lookup(variable, isArray: false) is { } v:
                if (v.Register is not null)
                {
                    Value(value, 0, v.Register, note); // compute straight into the variable's register
                }
                else
                {
                    var register = Value(value, 0);
                    Instruction($"sw {register}, {v.Label}", note);
                }
                break;
            case IndexExpr element when Lookup(element, isArray: true) is { } array:
                var valueRegister = Value(value, 0);
                var index = Value(element.Index, 1);
                Instruction($"sll $t1, {index}, 2", "Byte offset = index * 4");
                Instruction($"sw {valueRegister}, {array.Label}($t1)", note);
                break;
        }
    }

    private void EmitPrint(object argument, bool asChar)
    {
        switch (argument)
        {
            case string text:
                Instruction("li $v0, 4");
                Instruction($"la $a0, {StringLabel(text)}");
                Instruction("syscall", $"Print \"{text}\"");
                break;
            case NumberExpr { IsChar: true } character:
                Instruction("li $v0, 11");
                Instruction($"li $a0, {character.Value}");
                Instruction("syscall", $"Print {CharText(character.Value)}");
                break;
            case Expr expression:
                // Evaluate first: the value may itself use $v0 (e.g. print(readInt())).
                var constant = Fold(expression);
                var register = constant is null ? Value(expression, 0) : null;
                Instruction(asChar ? "li $v0, 11" : "li $v0, 1");
                Instruction(constant is { } c ? $"li $a0, {c}" : $"move $a0, {register}");
                Instruction("syscall", asChar ? $"Print {Text(expression)} as a character" : $"Print {Text(expression)}");
                break;
        }
    }

    // ---- Expressions ----

    /// <summary>
    /// Puts an expression's value in a register and returns it. With <paramref name="dest"/> the result goes
    /// exactly there (only the last instruction writes it). Without, a variable's own register is returned
    /// as-is and other values go to $t{k}; $t{k+1}.. are free for sub-expressions.
    /// </summary>
    private string Value(Expr expression, int k, string? dest = null, string? note = null)
    {
        if (k >= TempRegisters)
        {
            Error(expression, "Expression is too deeply nested; split it into smaller steps using extra variables.");
            return "$t9";
        }
        var target = dest ?? $"$t{k}";
        if (Fold(expression) is { } constant)
        {
            Instruction($"li {target}, {constant}", note);
            return target;
        }

        switch (expression)
        {
            case VariableExpr variable when Lookup(variable, isArray: false) is { } v:
                if (v.Register is { } register)
                {
                    if (dest is null) return register;
                    if (dest != register) Instruction($"move {dest}, {register}", note);
                    return dest;
                }
                Instruction($"lw {target}, {v.Label}", note);
                return target;

            case IndexExpr element when Lookup(element, isArray: true) is { } array:
                var index = Value(element.Index, k);
                Instruction($"sll $t{k}, {index}, 2", "Byte offset = index * 4");
                Instruction($"lw {target}, {array.Label}($t{k})", note);
                return target;

            case CallExpr call:
                var readInt = call.Name == "readInt";
                Instruction(readInt ? "li $v0, 5" : "li $v0, 12");
                Instruction("syscall", readInt ? "Read an integer" : "Read a character");
                Instruction($"move {target}, $v0", note);
                return target;

            case UnaryExpr { Op: "-" } negate:
                Instruction($"neg {target}, {Value(negate.Operand, k)}", note);
                return target;

            case UnaryExpr { Op: "!" } notExpr:
                Instruction($"seq {target}, {Value(notExpr.Operand, k)}, 0", note ?? "Logical not");
                return target;

            case BinaryExpr { Op: "&&" or "||" } logical:
                LogicalValue(logical, target, k, note);
                return target;

            case BinaryExpr binary:
                return BinaryValue(binary, target, k, note);
        }
        return target; // undeclared names are already reported
    }

    private static readonly Dictionary<string, string> RegisterOps = new()
    {
        ["+"] = "add", ["-"] = "sub", ["*"] = "mul", ["/"] = "div", ["%"] = "rem",
        ["=="] = "seq", ["!="] = "sne", ["<"] = "slt", ["<="] = "sle", [">"] = "sgt", [">="] = "sge"
    };

    private string BinaryValue(BinaryExpr binary, string target, int k, string? note)
    {
        var left = Value(binary.Left, k);
        if (Fold(binary.Right) is { } constant)
        {
            if (binary.Op is "/" or "%" && constant == 0) { Error(binary.Right, "Division by zero."); return target; }
            var fits16 = constant is >= short.MinValue and <= short.MaxValue;
            var instruction = binary.Op switch
            {
                "+" when fits16 => $"addi {target}, {left}, {constant}",
                "-" when constant != int.MinValue && -constant is >= short.MinValue and <= short.MaxValue => $"addi {target}, {left}, {-constant}",
                "<" when fits16 => $"slti {target}, {left}, {constant}",
                "<" => null,
                _ => $"{RegisterOps[binary.Op]} {target}, {left}, {constant}"
            };
            if (instruction is not null) { Instruction(instruction, note); return target; }
        }
        var right = Value(binary.Right, k + 1);
        Instruction($"{RegisterOps[binary.Op]} {target}, {left}, {right}", note);
        return target;
    }

    // && and || as values (0 or 1), with short-circuit evaluation.
    private void LogicalValue(BinaryExpr logical, string target, int k, string? note)
    {
        if (logical.Op == "&&")
        {
            var labels = NewLabels("andFalse", "andDone");
            JumpIfFalse(logical, labels[0], k);
            Instruction($"li {target}, 1", note);
            Instruction($"j {labels[1]}");
            Label(labels[0], null);
            Instruction($"li {target}, 0", note);
            Label(labels[1], null);
        }
        else
        {
            var labels = NewLabels("orTrue", "orDone");
            JumpIfTrue(logical, labels[0], k);
            Instruction($"li {target}, 0", note);
            Instruction($"j {labels[1]}");
            Label(labels[0], null);
            Instruction($"li {target}, 1", note);
            Label(labels[1], null);
        }
    }

    // ---- Conditions: branch directly instead of computing 0/1 ----

    private static readonly Dictionary<string, string> BranchFor = new()
    {
        ["=="] = "beq", ["!="] = "bne", ["<"] = "blt", ["<="] = "ble", [">"] = "bgt", [">="] = "bge"
    };

    private static readonly Dictionary<string, string> Inverse = new()
    {
        ["=="] = "!=", ["!="] = "==", ["<"] = ">=", ["<="] = ">", [">"] = "<=", [">="] = "<"
    };

    private void JumpIfFalse(Expr condition, string label, int k, string? context = null) => Jump(condition, label, k, whenTrue: false, context);
    private void JumpIfTrue(Expr condition, string label, int k, string? context = null) => Jump(condition, label, k, whenTrue: true, context);

    private void Jump(Expr condition, string label, int k, bool whenTrue, string? context = null)
    {
        if (Fold(condition) is { } constant)
        {
            if ((constant != 0) == whenTrue) Instruction($"j {label}", $"Always → {label}");
            return;
        }

        switch (condition)
        {
            case UnaryExpr { Op: "!" } notExpr:
                Jump(notExpr.Operand, label, k, !whenTrue, context);
                return;

            // a && b: false if either is false; true only if both are true.
            case BinaryExpr { Op: "&&" } andExpr when !whenTrue:
                Jump(andExpr.Left, label, k, whenTrue: false, context);
                Jump(andExpr.Right, label, k, whenTrue: false);
                return;
            case BinaryExpr { Op: "&&" } andExpr:
            {
                var skip = NewLabels("andSkip")[0];
                Jump(andExpr.Left, skip, k, whenTrue: false, context);
                Jump(andExpr.Right, label, k, whenTrue: true);
                Label(skip, null);
                return;
            }

            // a || b: true if either is true; false only if both are false.
            case BinaryExpr { Op: "||" } orExpr when whenTrue:
                Jump(orExpr.Left, label, k, whenTrue: true, context);
                Jump(orExpr.Right, label, k, whenTrue: true);
                return;
            case BinaryExpr { Op: "||" } orExpr:
            {
                var skip = NewLabels("orSkip")[0];
                Jump(orExpr.Left, skip, k, whenTrue: true, context);
                Jump(orExpr.Right, label, k, whenTrue: false);
                Label(skip, null);
                return;
            }

            case BinaryExpr comparison when BranchFor.ContainsKey(comparison.Op):
            {
                // The branch is taken when the comparison has the wanted truth value.
                var op = whenTrue ? comparison.Op : Inverse[comparison.Op];
                var mnemonic = BranchFor[op];
                var note = $"if {Text(comparison.Left)} {op} {Text(comparison.Right)} → {label}";
                var left = Value(comparison.Left, k);
                if (Fold(comparison.Right) is { } right)
                {
                    if (right == 0 && op is "==" or "!=")
                        Instruction($"{(op == "==" ? "beqz" : "bnez")} {left}, {label}", note);
                    else
                        Instruction($"{mnemonic} {left}, {right}, {label}", note);
                }
                else
                {
                    Instruction($"{mnemonic} {left}, {Value(comparison.Right, k + 1)}, {label}", note);
                }
                return;
            }

            default:
            {
                var value = Value(condition, k);
                var text = Text(condition);
                Instruction($"{(whenTrue ? "bnez" : "beqz")} {value}, {label}", whenTrue ? $"if {text} → {label}" : $"if !({text}) → {label}");
                return;
            }
        }
    }

    // ---- Constant folding (literals and arithmetic on them) ----

    private static int? Fold(Expr expression) => expression switch
    {
        NumberExpr number => number.Value,
        UnaryExpr { Op: "-" } u when Fold(u.Operand) is { } v => unchecked(-v),
        UnaryExpr { Op: "!" } u when Fold(u.Operand) is { } v => v == 0 ? 1 : 0,
        BinaryExpr b when Fold(b.Left) is { } l && Fold(b.Right) is { } r => b.Op switch
        {
            "+" => unchecked(l + r),
            "-" => unchecked(l - r),
            "*" => unchecked(l * r),
            "/" when r != 0 && !(l == int.MinValue && r == -1) => l / r,
            "%" when r != 0 && !(l == int.MinValue && r == -1) => l % r,
            "==" => l == r ? 1 : 0,
            "!=" => l != r ? 1 : 0,
            "<" => l < r ? 1 : 0,
            "<=" => l <= r ? 1 : 0,
            ">" => l > r ? 1 : 0,
            ">=" => l >= r ? 1 : 0,
            "&&" => l != 0 && r != 0 ? 1 : 0,
            "||" => l != 0 || r != 0 ? 1 : 0,
            _ => null
        },
        _ => null
    };

    // ---- Pseudocode text for comments ----

    private static int PrecedenceOf(string op) => op switch
    {
        "||" => 1, "&&" => 2, "==" or "!=" => 3, "<" or "<=" or ">" or ">=" => 4, "+" or "-" => 5, _ => 6
    };

    private static string Text(Expr expression, int parentPrecedence = 0) => expression switch
    {
        NumberExpr { IsChar: true } c => CharText(c.Value),
        NumberExpr n => n.Value.ToString(System.Globalization.CultureInfo.InvariantCulture),
        VariableExpr v => v.Name,
        IndexExpr ix => $"{ix.Name}[{Text(ix.Index)}]",
        CallExpr call => $"{call.Name}()",
        UnaryExpr u => u.Op + Text(u.Operand, 7),
        BinaryExpr b => Wrap($"{Text(b.Left, PrecedenceOf(b.Op))} {b.Op} {Text(b.Right, PrecedenceOf(b.Op) + 1)}", PrecedenceOf(b.Op) < parentPrecedence),
        _ => "?"
    };

    private static string Wrap(string text, bool parenthesize) => parenthesize ? $"({text})" : text;

    private static string CharText(int value) => value switch
    {
        '\n' => "'\\n'",
        '\t' => "'\\t'",
        0 => "'\\0'",
        >= 32 and < 127 => $"'{(char)value}'",
        _ => $"character {value}"
    };

    private static string Trim(string source) => source.TrimEnd(';').Trim();

    // ---- Names and labels ----

    private Variable? Lookup(Expr reference, bool isArray)
    {
        var name = reference is VariableExpr v ? v.Name : ((IndexExpr)reference).Name;
        if (!_variables.TryGetValue(name, out var variable))
        {
            Error(reference, $"'{name}' is not declared. Declare it first, e.g. int {name} = 0;");
            return null;
        }
        if (isArray && variable.ArraySize is null) { Error(reference, $"'{name}' is not an array, so it cannot be indexed with [...]."); return null; }
        if (!isArray && variable.ArraySize is not null) { Error(reference, $"'{name}' is an array; use an index like {name}[0]."); return null; }
        return variable;
    }

    // A .data label for a variable: its own name, unless that is taken (labels are case-insensitive).
    private string DataLabel(string name)
    {
        var label = name;
        while (_usedLabels.Contains(label)) label = "var_" + label;
        _usedLabels.Add(label);
        return label;
    }

    // Labels for one construct, numbered together: loop/endLoop, then loop2/endLoop2, ...
    private string[] NewLabels(params string[] bases)
    {
        var number = _labelNumbers.GetValueOrDefault(bases[0]);
        string[] names;
        do
        {
            number++;
            var suffix = number == 1 ? "" : number.ToString(System.Globalization.CultureInfo.InvariantCulture);
            names = bases.Select(b => b + suffix).ToArray();
        } while (names.Any(_usedLabels.Contains));
        _labelNumbers[bases[0]] = number;
        foreach (var name in names) _usedLabels.Add(name);
        return names;
    }

    // Strings are named after their text: "FizzBuzz\n" -> fizzBuzz, "\n" -> newline.
    private string StringLabel(string text)
    {
        if (_stringLabels.TryGetValue(text, out var existing)) return existing;
        var words = Regex.Matches(Regex.Replace(text, @"\\.", " "), "[A-Za-z0-9]+").Select(m => m.Value).Take(3).ToList();
        var name = words.Count == 0
            ? text switch { "\\n" => "newline", " " => "space", "\\t" => "tab", ", " => "comma", _ => "text" }
            : string.Concat(words.Select((w, i) => i == 0 ? char.ToLowerInvariant(w[0]) + w[1..] : char.ToUpperInvariant(w[0]) + w[1..]));
        if (!char.IsLetter(name[0])) name = "str" + name;
        if (name.Length > 24) name = name[..24];

        var label = name;
        for (var n = 2; _usedLabels.Contains(label); n++) label = name + n;
        _usedLabels.Add(label);
        _stringLabels[text] = label;
        _strings.Add((label, text));
        return label;
    }

    // ---- Output ----

    private static string WithComment(string line, string? note) =>
        note is null ? line : line.PadRight(CommentColumn - 1) + " # " + note;

    private void Label(string label, string? note)
    {
        if (!_lastLineBlank) _text.AppendLine();
        _text.AppendLine(WithComment(label + ":", note));
        _lastLineBlank = false;
        _lastLineLabel = true;
    }

    private void Instruction(string instruction, string? note = null)
    {
        _text.AppendLine(WithComment("    " + instruction, note));
        _lastLineBlank = false;
        _lastLineLabel = false;
    }

    private void Error(Node node, string message) => Error(node.Line, node.Column, message);
    private void Error(int line, int column, string message) => _errors.Add(new PseudocodeError(line, column, message));
}
